name: Executable

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - '1.5'
        os:
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: tag number
        run : echo ${{ github.ref }}
