name: Executable

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - '1.5'
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Branch name
        id: branch_name
        run:
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compress binaries
        run: tar -cvzf deps/vchdfe-${SOURCE_TAG}-${{ matrix.os }}.tar.gz deps/vchdfe
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deps/vchdfe-${SOURCE_TAG}-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
