name: Executable

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - '1.5'
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Compress binaries
        run: tar -cvzf deps/vchdfe-${{env.GIT_TAG_NAME}}-${{ matrix.os }}.tar.gz deps/vchdfe
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deps/vchdfe-${{env.GIT_TAG_NAME}}-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
