name: Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - '1.5'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: make new directory
        run: mkdir deps/vchdfe/bin/
      - name: Copy the test file into the tar file
        run: cp README.md deps/vchdfe/bin/README.md
      - name: Remove the files from the precompilation
        run: rm deps/vchdfe/bin/README.md
      - name: Compress binaries
        run: tar -cvzf deps/vchdfe-${{ github.event.release.tag_name }}-${{ matrix.os }}.tar.gz deps/vchdfe
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deps/vchdfe-${{ github.event.release.tag_name }}-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
