name: LaTeX

on: 
  push:
    paths:
    - 'docs/tex/rough_notes.tex'

jobs:
  latex-job:
    runs-on: ubuntu-latest
    steps:
      
      - name: download paper repo
        uses: actions/checkout@v1
      - name: build pdf 
        uses: xu-cheng/latex-action@1.3.0
        with:
          root_file: rough_notes.tex
          working_directory: tex 
      - name: stash pdf
        run: |
          mv docs/tex/rough_notes.pdf $HOME # cache the file
      - name: checkout gh_actions_builds branch
        uses: actions/checkout@v1
        with:
          ref: gh_actions_builds 
      - name: commit pdf
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mv $HOME/rough_notes.pdf $(pwd) # bring it back 
          git add rough_notes.pdf
          git commit -m "Add changes"
      - name:  push pdf
        uses: ad-m/github-push-action@v0.5.0
        with: 
          branch: gh_actions_builds 
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
